version: "3.9"

services:

  ipor-scrapper-aave-v1-es:
    container_name: scrapper-aave-v1-es
    image: elasticsearch:7.16.2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - scrapper-aave-v1-es-data:/usr/share/elasticsearch/data
    environment:
      - TZ=Europe/Warsaw
      - node.name=scrapper-aave-v1-es-node1
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - scrapper-aave-v1-net

  ipor-scrapper-aave-v1-kibana:
    container_name: scrapper-aave-v1-kibana
    image: kibana:7.16.2
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - scrapper-aave-v1-es
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./containers/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - scrapper-aave-v1-net

volumes:
  scrapper-aave-v1-es-data:
    name: scrapper-aave-v1-es-data
    driver: local

networks:
  scrapper-aave-v1-net:
    driver: bridge
